### ISSUE TITLE
[Bug]: Authentication token value is set to Redacted after next terraform apply

### ISSUE THREAD

**Issue by Tautcius** [komminarlabs/terraform-provider-influxdb#49]
### Terraform Core Version

1.9.2

### InfluxDB Provider Version

3.0.0

### Affected Resource(s)

influxdb_authorization

### Expected Behavior

Each time i run terraform this resource is getting recreated:
  # module.clients["provincijos-mesa"].influxdb_authorization.client has changed
  ~ resource "influxdb_authorization" "client" {
        id          = "0d8bc6ec2a4c7000"
      ~ token       = (sensitive value)
        # (7 unchanged attributes hidden)
    }

  # module.clients["tagai-test"].influxdb_authorization.client has changed
  ~ resource "influxdb_authorization" "client" {
        id          = "0d8bc6ec2a8f0000"
      ~ token       = (sensitive value)
        # (7 unchanged attributes hidden)
    }

This recource is in a module

### Actual Behavior

in recreates and saves token value in Kubernetes secret.

I expect to get token value but instead I get this:

redacted

I think it is reading influx cli output, but not actual new token value that is generated

### Terraform Configuration Files

resource "kubernetes_namespace" "client" {
  metadata {
    name = var.client
  }
}

data "influxdb_organization" "iot" {
  name = var.org_name
}

resource "influxdb_bucket" "client" {
  org_id           = data.influxdb_organization.iot.id
  name             = var.client
  description      = "This is a bucket to for clien ${var.client} to read/write to"
  retention_period = 15552000 // 180 days
}

resource "influxdb_authorization" "client" {
  org_id      = data.influxdb_organization.iot.id
  description = "Access to ${var.client} bucket"

  permissions = [{
    action = "read"
    resource = {
      id   = influxdb_bucket.client.id
      org_id = data.influxdb_organization.iot.id
      type = "buckets"
    }
    },
    {
      action = "write"
      resource = {
        id   = influxdb_bucket.client.id
        org_id = data.influxdb_organization.iot.id
        type = "buckets"
      }
  }]
}

resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "kubernetes_secret_v1" "influxdb_secret" {
  metadata {
    name = "influxdb-token"
    namespace = kubernetes_namespace.client.metadata[0].name
  }

  data = {
    INFLUXDB_TOKEN = influxdb_authorization.client.token
    INFLUXDB_BUCKET = influxdb_bucket.client.name
    INFLUXDB_ORG = data.influxdb_organization.iot.name
    MQTT_USER = "telegraf-${var.client}"
    MQTT_PASSWORD = random_password.password.result
    CLIENT_TOPIC = replace(var.client, "-", "_")
  }

  type = "Opaque"
}

### Steps to Reproduce

terraform plan
terraform apply

### Important Factoids

I can share my state file in private messaging or provide additional info what is not secret.

**Comment by thulasirajkomminar** [comment]
@Tautcius Thanks for opening an issue. I do not understand the details. I see the expected behaviour you added `Each time i run terraform this resource is getting recreated`. Is this something you want or is this the actual behaviour now? 
Could you share the terraform provider version and the influxdb flavour and version?

**Comment by thulasirajkomminar** [comment]
@Tautcius 
**Update:** Influxdb v2 cloud and oss api behaves different. Creating a patch release now.

**Comment by thulasirajkomminar** [comment]
@Tautcius released new version [v1.1.1](https://github.com/komminarlabs/terraform-provider-influxdb/releases/tag/v1.1.1)

**Comment by Tautcius** [comment]
Thanks sorry for late response. I am using influxdb serverless
